### ISSUE TITLE
Process for tutorial creation

### ISSUE THREAD

**Issue by jlaura** [DOI-USGS/asc-public-docs#30]
Seeing PRs coming in for tutorials, I am struck that having additional process in place may make for a better experience for the issue openers, the person(s) creating the documentation, and the reviewers.

Specifically, I would propose (1) that issue openers have a requirement explicitly identify which category the documentation falls into, e.g., this is a tutorial that demonstrates, or this is concept material, etc and the docs will 'show how to do X or describe Y). Folks can then iterate on the issue before anyone even starts to be like: 'this is good, but I think it should be written in a different style because XYZ'. That way the person that creates the docs has a target to hit in terms of the what.
 
Then, (2) I think having an outline (as a PR marked as a draft?) from the documentation creator makes sense so that they can describe the sections they are envisioning before they start the tedious part of writing / screen captures / research, etc.
 
This way the PR can be iterated on **before** the hard work of creating images, writing lots of text, etc. occurs. 

I think these are both process updates and not something that can be automated away.

**Comment by Kelvinrr** [comment]
I think we can leverage issue templates to pre-populate the issue with whatever information we expect from authors. Similar to how we would for software repos (bug, feature add, question, etc.) except for our documentation types (getting-started tutorial, how-to, explanation or software manual).

Some thoughts on what we might require, not definitive about any of it: 

* Getting-Started tutorials:
  *  Issue: at least have a task that needs to have the lesson to be learned (e.g. how do map projections work in ISIS with CSM) and a task to be done (e.g. create a map projected image using CSM). 
  * Outline: have a list of steps that would have to be completed. Maybe as markdown or a jupyter notebook with only headers? 
* How-tos: 
  * Issue: should define the general problem that needs to be solved in the issue (e.g. how-to append to the CSM search directories). 
  * Outline: for how-to is a little tricky, since they are often very short. Maybe not require them? IDK if that's a good idea though. 
* Concepts: 
  * Issue: should have a pending title and scope of the write-up. 
  * Outline: can be similar to tutorials, markdown with headers and a TOC. But additionally, maybe having a list of sources during the outline stage so we know where any fact-based claims would be coming from. 
* Manuals:
  * Issue: What is the software? Why and how does it relate to astro? Who maintains the software manual? How is it maintained and where are regular updates pushed? Link to the existing docs. 
  * Outline: probably wouldn't need one as it would be a PR adding to the list of software manuals. 

If we decide to outline in PRs, we will need to consider forcing drafts for new PRs which, from poking around the settings, there doesn't seem to be an option to enforce it via GH, which would be a little annoying.

**Comment by jrcain-usgs** [comment]
How big of an outline are we thinking?  Would it be a good idea to comment outlines in issues to workshop them (vs. putting outlines in draft PRs)?

**Comment by Kelvinrr** [comment]
I feel draft PRs are still best since it allows in line comments. Lends itself well to the review process.

**Comment by AustinSanders** [comment]
Initial guidelines are roughed in via #49.  Could use some discussion + revisions

**Comment by AustinSanders** [comment]
The process described here was codified in #49.  Closing this issue, but we can reopen if changes are necessary
