### ISSUE TITLE
How-to: create a CSM model 

### ISSUE THREAD

**Issue by Kelvinrr** [DOI-USGS/asc-public-docs#33]
A how-to guide explaining CSM models and how to create a new model would be very helpful. 

Some knowledge the reader should have by the end: 
* What is a CSM model? Why is it different than an ALE driver? 
* What is the CSM state string and how is it different than the ISD? 
* What functions need to be written and why?

**Comment by AustinSanders** [comment]
This issue may have some crossover with some of the docs in #36.  It may be worth linking / referencing or adding to the existing docs instead of adding more pages.  Specifically [this section](https://astrogeology.usgs.gov/docs/concepts/sensor-models/sensor-model-software/#usgs-community-sensor-model-usgscsm)

**Comment by Kelvinrr** [comment]
I think if we add the link to that section we can close this since that notebook already addresses the issue. But it's worth adding that extra context
